---
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Load Composer cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-suggest

      - name: Run tests
        run: |
          vendor/bin/php-cs-fixer fix --dry-run -v --no-ansi
          vendor/bin/phpspec run --format=dot --no-ansi
